spring.application.name=content-service
server.port=8083

spring.datasource.url=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=7e38706f7274666f6c696f2d6a77742d7365637265742d6b6579202d207468697320697320766572792073656375726520616e6420636f6e666964656e7469616c
jwt.expiration=86400000

logging.level.com.portfolio.content=DEBUG

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
